title: Robin B. Rubangura  

logo: My professional picture.png  # Use a relative path to logo image 






description: Data Enthusiast. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: robinrubangura@gmail.com
