title: Robin B.R.

logo: My professional picture.jpg  # Use a relative path to logo image 

description: Freelancer in Data Analytics 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: robinrubangura@gmail.com
