title: Robin R.

logo:  # Use a relative path to logo image 

description: Freelancer|Data Analytics 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: robinrubangura@gmail.com
