title: Robin R.

logo:  DIG734.jpg 

description: Data Analyst | Sports lover

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: robinrubangura21@gmail.com
