title: Robin R.

logo:  # Use a relative path to logo image 

description: MSc Student| Passionate about data

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: robinrubangura21@gmail.com
